### ISSUE TITLE
prop decorators defined in a different compilation unit?

### ISSUE THREAD

**Issue by hugebdu** [Hookyns/tst-reflect#27]
Trying to use class prop decorator - works perfect when resides in the same source file with the property being decorated, but if the decorator is imported from another source file, I get `Property#decorators` empty

**Comment by hugebdu** [comment]
also capturing decorator args would be really great (primitives & enums)
```
class Entity {
  @Orm.Id(Orm.IdKind.AutoGenerated)
  id: string;
}
```

**Comment by Hookyns** [comment]
> also capturing decorator args would be really great (primitives & enums)
> 
> ```
> class Entity {
>   @Orm.Id(Orm.IdKind.AutoGenerated)
>   id: string;
> }
> ```

This is related with #7 

There is no problem to support property decorators and allow them to get type of class via generic type. So it is possible to start from other side from that decorator, with all the runtime arguments of that decorator and get type of class. That's the point in #7.

Your point is good too. If it is constant value, capture it.
So add `Decorator.arguments: any[]`?

**Comment by hugebdu** [comment]
> Decorator.arguments: any[]?

Sounds good 👍 

Thanks

**Comment by Hookyns** [comment]
Fixed. Will be publish with other bug fixes in next version.

Contains fix of the decorators from different module and `arguments: Array<any>` for decorators. 
Arguments must be `Literal` (string, number, boolean or enum. It can be value from `const` variable, even imported).
It is possible to allow Object litrals too, but it's a little tricky... I've kept it simple for this time...

```typescript
import {
	getType,
	reflect
}                     from "tst-reflect";
import { SomeEnum }   from "./SomeEnum";
import { SomeString } from "./SomeType";

const MyString = "SomeType";

function klass<TType>(str: string, num: number, enu: SomeEnum)
{
	console.log("klass", str, num, enu, getType<TType>());
	return function <T>(Constructor: { new(...args: any[]): T }) {
	};
}

function property(str: string, num: number, enu: SomeEnum, any: any)
{
	console.log("property", str, num, enu, any);
	return function (_, __) {};
}

@klass(MyString, 5, SomeEnum.One)
class A
{
	@property("Foo property", 5, SomeEnum.One, { foo: "f", bar: 5, baz: SomeEnum.Two })
	foo: string;

	@property(SomeString, 5, SomeEnum.Two, true)
	get bar(): number
	{
		return 0;
	}
}
```

**Comment by Hookyns** [comment]
Available from:

`tst-reflect@0.7.0-alpha.0`
`tst-reflect-transformer@0.9.0-beta.2`

**Comment by hugebdu** [comment]
awesome!
thanks @Hookyns
