### ISSUE TITLE
Runtime generic class type parameters

### ISSUE THREAD

**Issue by Hookyns** [Hookyns/tst-reflect#30]
Support class generic parameters same ways the method generic parameters.

```typescript
class Foo<TGenericClassType>
{
    doSomething() {
        getType<TGenericClassType>();
    }
}
```

**Comment by AbdulRafaySiddiqui** [comment]
Hey, First of all, thanks for making this amazing package, really appreciate the effort.

Can you please guide me on how and where to add the support for generics, I am trying to build a utility function that can return default values for an interface, and this package is the only thing that can make it happen as far as I know.

```
interface ISampleInterface {
  name: string;
  age: number;
  alive: boolean;
  wishlist: string[];
  somethingOptional?: number;
  nestedObj: {
    hello: string;
    bye: number;
    hi: string[];
  };
}

// preferred way
const sampleObj: ISampleInterface = getDefaultValues<ISampleInterface>();

// available for now
const sample: ISampleInterface = getDefaultValues<ISampleInterface>(getType<ISampleInterface>());

//output
{
  name: '',
  age: 0,
  alive: false,
  wishlist: [],
  complexObj: { hello: '', bye: 0, helloBye: [] }
}

"getDefaultValues" just read the types with getType<T>() and construct the obj with default values
```

Thanks!

**Comment by Hookyns** [comment]
Hi @AbdulRafaySiddiqui, TY.

Something like this?
https://stackblitz.com/edit/tst-reflect-example-get-default-values?file=index.ts

**Comment by AbdulRafaySiddiqui** [comment]
oh great, I was doing the same thing, but with arrow function and it was giving this error `ReferenceError: __genericParams__ is not defined`, strange :/
I thought it was some limitation of the package, but changed to normal function just like yours and now it works :)

Thanks, @Hookyns

**Comment by Hookyns** [comment]
Implemented in `the Next` version.

**Comment by Igorjan94** [comment]
It works fine for `getType<Foo<T>>()`, but fails from inside class like in your first message:

~~~~~
class Foo<T>
{
    doSomething() {
        const type: Type = getType<T>()
        console.log(type)
    }
}
const temp = new Foo<string>()
temp.doSomething()
~~~~~

with `ReferenceError: __genericParams__ is not defined`

**Comment by Hookyns** [comment]
@Igorjan94 Yes, it is not implemented in the current version 0.x, but it is implemented in the new rewriten version of this package (I call it `The Next` version), which is not public yet. It'll be v1.0 version.

Example you posted will be working, such as:

```typescript
class Foo<T>
{
	constructor(bar: T, ...rest: any[]) {
		getType<T>();
	}

	doSomething<U>() {
		getType<T>();
		getType<U>();
	}
}

// new,
new Foo<string>("bar").doSomething();

// or Reflect.construct<T>(Function, args: any[], newTarget: Function),
Reflect.construct<Foo<string>>(Foo, ["some", "args"]).doSomething();

// or Reflect.construct(Function, typeArgs: Type[], args: any[], newTarget: Function),
Reflect.constructGeneric(Foo, [getType<string>()], ["some", "args"]).doSomething();

// or this too.
function baz<T>(Ctor: Function, ...args: any[]) {
	Reflect.constructGeneric(Ctor, [getType<T>()], args).doSomething();
}

baz<string>(Foo, "some", "args");
```

**Comment by Igorjan94** [comment]
Ah, sorry, I thought it's available now, haven't thought that it's private version. Can't wait to test it out!
