### ISSUE TITLE
Get type args for things like Promise<T>

### ISSUE THREAD

**Issue by bjsi** [Hookyns/tst-reflect#32]
Impressed by this project, I loved the reflection and meta programming possibilities in C# and love that you are adding it into TS!

I am wondering if it would be possible to get full type info for things like `Promise<T>`?

Eg. currently for `getType<Promise<string>>()` I get:

```
{
  "_name": "PromiseConstructor",
  "_fullName": "PromiseConstructor",
  "_kind": 4,
  "_constructors": [],
  "_properties": [],
  "_methods": [],
  "_decorators": [],
  "_typeParameters": [],
  "_ctorDesc": {},
  "_isUnion": false,
  "_isIntersection": false,
  "_types": [],
  "_typeArgs": [],
  "_baseType": {
    "_name": "Object",
    "_fullName": "Object",
    "_kind": 2,
    "_constructors": [],
    "_properties": [],
    "_methods": [],
    "_decorators": [],
    "_typeParameters": [],
    "_ctorDesc": {},
    "_isUnion": false,
    "_isIntersection": false,
    "_types": [],
    "_typeArgs": []
  }
}
```

Would be happy to help however I can in implementing this, if you are able to guide me a bit to the correct areas of the codebase :)

**Comment by Hookyns** [comment]
Hello @bjsi,
I'm  currently working on a big update with a lot of changes including support of all the native types (including Promise, Symbol, TypedArrays etc.) _[more info](https://twitter.com/hookyns/status/1498536859126874115) about upcoming update is on my twitter; and I will tweet the progress._ It will take me about week to finish it. 
But it will be quite easy to fix the Promise in current version IMHO. I think I can publish fix in 30 minutes,.. challenge accepted! 😄 

Anyway, we are open to contributions. 🙂 But I have to finish that update first. Contributions would be unmergeable cuz of that.

**Comment by bjsi** [comment]
Amazing thanks @Hookyns :)

**Comment by Hookyns** [comment]
Done.

```typescript
import { getType } from "tst-reflect";

const promiseType = getType<Promise<string>>();

if (promiseType.isPromise())
{
	console.log(promiseType.getTypeArguments()[0].isString()); // > true
}
```

I've just released new versions `tst-reflect@0.7.4` and `tst-reflect-transformer@0.9.4`.
Try it. 🙂

**Comment by bjsi** [comment]
Wow you are the best :) many thanks

**Comment by Hookyns** [comment]
I thank you. 🙂 
You've just improved this project. I focus on the big upcoming update so I miss some issues.
