### ISSUE TITLE
Unable to get type arguments of class

### ISSUE THREAD

**Issue by avin-kavish** [Hookyns/tst-reflect#49]
It looks like reading the type arguments of a class doesn't work. Inner Type of type aliases resolve correctly, but not classes.

```ts
type Foo<Type> = Type & {}

class Bar<Type> {}

@inject()
export class Baz {
  foo: Foo<string>   // type.innerTypes contains string

  bar: Bar<string>   // type.innerTypes is empty. type.getTypeParameters() returns Type. type.getTypeArguments() is empty
}
```

**Comment by Hookyns** [comment]
Fixed in tst-reflect-transformer@0.9.11

But `type` work differently than other generic types. `type` is resolved to it's definition. So `type Foo<T> = T & {}` is just union `T & {}`, cuz `Foo` does not rly exist.

Check this [StackBlitz](https://stackblitz.com/edit/tst-reflect-issue-49?file=index.ts,index.js) out.

**Comment by avin-kavish** [comment]
thanks for the fix!

While I'm here, isn't it possible to get types from the reference to a class ? i.e. `getType(Foo)` instead of `getType<Foo>()`

**Comment by Hookyns** [comment]
@avin-kavish 
It is now in `tst-reflect@0.7.8`.

It was possible to get type of value `getType(new Foo())`; just one line and you are able to get type of class itself `getType(Foo)`.

**Comment by avin-kavish** [comment]
that's great!

I was considering the following about `tst-reflect` usage,

1. Can't we use a decorator directly, without having to call a method that returns a decorator?

```tsx
/**
 * @reflect
 */
function inject<TType extends Constructor>(ctor: TType) {
    const typeInfo = getType<TType>()
}

// usage
@inject
class Foo {}
```

2. Can't we collect type info for all classes/interfaces in a project without using decorators? Maybe it's too slow?

**Comment by Hookyns** [comment]
@avin-kavish 
1. You can. https://github.com/Hookyns/tst-reflect/blob/main/tests/src/11-generic-class-decorator.ts
2. Now all the types passed to `getType<T>()` and types decorated by decorators marked by `@reflect` are "reflected".
\
[`Next`](https://github.com/Hookyns/tst-reflect/blob/v0.10/packages/abstract/src/Module.ts) version is prepared for generating metadata about all the modules and types.
\
It's in progress and the latest progress is private until publish of final version.
