### ISSUE TITLE
is there a typescript runtime validator?

### ISSUE THREAD

**Issue by masx200** [Hookyns/tst-reflect#57]
is there a typescript runtime validator?

**Comment by Hookyns** [comment]
Hi,
what kind of validator you mean? To validate what?

**Comment by masx200** [comment]
```ts
const validator=new Validator<{foo:string,bar:number}>()

validator.validate(JSON.parse("something"))
```

**Comment by Hookyns** [comment]
There is no such validator inside this project. This project is clear Reflection system. 

Validator might be some other package using this package to implement the validation.
But such validation is quite simple and you can use built in `Type.isAssignableTo(someOtherType)` and runtime type construction via `getType(some runtime value)`.

Check this [https://stackblitz.com/edit/tst-reflect-validation?file=index.ts](StackBlitz).

**Comment by Hookyns** [comment]
But maybe you can use https://github.com/joeferner/tst-reflect-json-schema-generator and then u can use existing schema validators or maybe you'll find useful this https://github.com/ciricc/tst-defaults.

**Comment by masx200** [comment]
https://www.npmjs.com/package/typescript-is
