### ISSUE TITLE
How to share metastore between libraries and current project ?

### ISSUE THREAD

**Issue by leohubert** [Hookyns/tst-reflect#62]
I develop a library that uses tst-reflect and I want to share the metastore of a project with my library (and conversely, share the metastore of my library with the project).

In 1 word, have a common metastore.

Is it possible?

**Comment by Hookyns** [comment]
Hi @leohubert, check the discussion #58.

> Now the end application using reflection should generate types, even for an npm packages.
Package built with current version can contain metadata and the package can work with them and also package can work with Types from end application.

What is not supported yet is listing of all the types using `Type.getTypes()`. Well, it will work partly, but... it wasn't meant to work like this in current version. It will be available in the `next` version.

**Comment by leohubert** [comment]
Thanks for the reply @Hookyns! 

I'll see how I can help you to move forward :)

**Comment by Hookyns** [comment]
I've designed system for this in v1. Partially implemented.

**Comment by Hookyns** [comment]
Implemented for the v1. Not in the current version.
