### ISSUE TITLE
Types are being overwrritten across files in inline mode

### ISSUE THREAD

**Issue by avin-kavish** [Hookyns/tst-reflect#64]
`_ßr.Type.store.set(` calls in different files are overwriting each other when they have the same id.

Suggestion: I think the singleton behavior is good. It means I can access all the types of the library using `Type.store`. I think they just need unique IDs.

**Comment by avin-kavish** [comment]
https://gist.github.com/avin-kavish/a28e22c62275a63d1788624173d820fc

Search for `_ßr.Type.store.set(1729` in these two files.

**Comment by Hookyns** [comment]
Whole `typelib` mode is weird in current version. Do you need that mode now?

`next` version will be based on one standard shared static storage, ttly reworked.

**Comment by avin-kavish** [comment]
Sorry I mean inline mode. That’s the problem.

**Comment by Hookyns** [comment]
Is that result of single build? Isn't it result of some hot reload or something? Or do you use incremental build?

_wow, 2k lines of metadata, seems like u rly use the reflection._ 😊

**Comment by avin-kavish** [comment]
Single build. Yeah I mean my project is at about 40k LOC now. It’s only
gonna get bigger :) it’s similar to asp net core in architecture

**Comment by Hookyns** [comment]
Something like I build.. 😄 
https://github.com/Hookyns/NetLeaf

**Comment by avin-kavish** [comment]
It’s similar but not exactly. In fact the apis are lot different. they are
more express like. Also djangolike.

**Comment by Hookyns** [comment]
Can I clone the repo to debug it? It's not possible that two types has the same ID; it is generated by TypeScript so it meant that TypeScript itself has duplicit type ids and I don't know why.
That conflict is with enum item so maybe it is some special case...

**Comment by avin-kavish** [comment]
Btw once it conflicted against array iterator built in type
