### ISSUE TITLE
[BUG] type metadata

### ISSUE THREAD

**Issue by uplight-dev** [Hookyns/tst-reflect#76]
**Describe the bug**

Type introspection doesn't seem to work on types extending other types.
Also, since types don't support decorators (i.e. @reflected), one has to manually write getType<TypeA>() in order to activate metadata generation for TypeA. Without this, the result contains invalid values, like "type.name : 'unknown'"

**The code causing the problem**
```typescript
type TypeA = {
	prop1: string
}

type TypeB = TypeA & {
  prop2: string,
  prop3: string
}

const t0: Type = getType<TypeA>();
const t1: Type = getType<TypeB>();
console.log(t1.getProperties())
```

**To Reproduce**
1. Build,
2. run,
3. see error...

**Expected behavior**
All properties including inherited ones should be displayed by ```console.log(t1.getProperties())```

**Runtime (please complete the following information):**
 - Node.js version: v18.10.0
 - TypeScript version: 4.8.4
 - Compiler: [ttypescript]
 - Bundler: [none]

**Additional context**

**Comment by Hookyns** [comment]
Hi @uplight-dev,
`TypeB` is just a type alias for `{ prop1: string } & { prop2: string, prop3: string }`, there is no `type` in the type checker, so it is described in metadata like an intersection.

So you have to do something like this:
```typescript
const t1: Type = getType<TypeB>();

const props = [];

if (t1.isUnionOrIntersection()) {
  props.push(...t1.types[0].getProperties(), ...t1.types[1].getProperties());
} else {
  props.push(...t1.getProperties());
}

console.log(props.map((p) => p.name + ': ' + p.type.name));
```

[Demo](https://stackblitz.com/edit/tst-reflect-overloads?file=index.ts) on StackBlitz.

**Comment by Hookyns** [comment]
BTW what do you mean by
> one has to manually write getType() in order to activate metadata generation for TypeA

TypeA is reflected correctly in the demo.

**Comment by uplight-dev** [comment]
Thank you, the demo works perfectly.

For the metadata generation, it's when you try to find the type in the TypeStore instead of using getType<TypeC>() construct.

Please see: [Demo](https://stackblitz.com/edit/tst-reflect-type-alias-intersection-eumknj?file=index.ts)

**Comment by Hookyns** [comment]
Okay, got it.

Sadly, this is intended behavior in the current version. This was intended as an optimisation, so only required types are reflected because of size of metadata (it would be megabytes for some projects). Type.find() was introduced later, but it is limited to reflected types.

New major version (alpha release is rly close) works in a different way (based on include/exclude options) so it works properly there.

**Comment by uplight-dev** [comment]
Looking forward to it! 
And thanks for this awesome lib, makes a difference for my use case!
