### ISSUE TITLE
[Question] How to get field type inside a decorator

### ISSUE THREAD

**Issue by Crash1988** [Hookyns/tst-reflect#86]
I am trying to use this package at runtime inside a field decorator.  I need to know that attr1 is type Number. any help how ?
```
import { getType } from "tst-reflect";


function logType(target : any, key : string) {
     const type = getType(target[key]);
     console.log(type); // i am trying to get what type is the field attr1
}

class Demo{ 
    @logType 
    public attr1 : number;

}
```

**Comment by Hookyns** [comment]
Hi @Crash1988,

this is a way how to do it in the current version: https://stackblitz.com/edit/tst-reflect-property-decorator?file=index.ts

**Comment by Hookyns** [comment]
I'm closing this. Feel free to reopen in case you'll face some issues with this solution.
